services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: react-vite-app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
