services:
  restaurant:
    build:
      context: ./Restaurent_MonoRepo_MicroService/restaurant/restaurantservice/restaurantservice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8081

  order:
    build:
      context: ./Restaurent_MonoRepo_MicroService/ordermanagement
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_URLS=http://+:8082

  payment:
    build:
      context: ./Restaurent_MonoRepo_MicroService/paymentservice
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_URLS=http://+:8083

  delivery:
    build:
      context: ./Restaurent_MonoRepo_MicroService/deliveryservice
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - ASPNETCORE_URLS=http://+:8084

  auth:
    build:
      context: ./Restaurent_MonoRepo_MicroService/authservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Restaurent_MonoRepo_MicroService/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - restaurant
      - order
      - payment
      - delivery
      - auth
