apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: email
  name: email
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: email
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/restaurent-monorepo-microservice-default: "true"
        io.kompose.service: email
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:8085
          image: email
          name: email
          ports:
            - containerPort: 8085
              hostPort: 8085
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
