apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1  # Number of Kafka pods to run
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          env:
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENER
              value: "kafka-service:9092"
            - name: KAFKA_LISTENER_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: ""  # No need for Zookeeper
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc  # Optional, if you're using persistent storage
