apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: manujayak/restaurant-service:latest
          ports:
            - containerPort: 6000
