apiVersion: v1
kind: Service
metadata:
  name: restaurantservice
spec:
  selector:
    app: restaurant
  ports:
    - port: 6000
      targetPort: 6000
      nodePort: 30600  # Optional, or let Kubernetes auto-assign
  type: NodePort
