version: '3.8'

services:
  restaurant-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    image: manujaya/restaurant-service:latest
    container_name: restaurant-service
