# Use an official Node.js 22.14.0 image as a parent image
FROM node:22.14.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy the rest of the application files
COPY . .

# Expose the correct application port
EXPOSE 8000

# Define the command to run the application
CMD ["node", "index.js"]