

services:
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - mynetwork

#run this 
# docker run -d \ -e ACCESS_TOKEN_SECRET=helloworldjwt_secret_key \ -e REFRESH_TOKEN_SECRET=thisisnotmyrefresh_secret_key \ authservice

# build command
# docker build -t authservice .
      

  authservice:
    build: .
    image: authservice
    container_name: authservice
    restart: always
    depends_on:
      - mongo
    # environment:
    #   - MONGO_URL=mongodb+srv://s1sewe35:s1sewe35@group35.z5ucr.mongodb.net/Microservice_AuthService?retryWrites=true&w=majority&appName=Group35
    #   - PORT=8080
    #   - ACCESS_TOKEN_SECRET=helloworldjwt_secret_key
    #   - REFRESH_TOKEN_SECRET=thisisnotmyrefresh_secret_key
    networks:
      - mynetwork
    ports:
      - "8080:8080"

networks:
  mynetwork:
    driver: bridge
